# Server
server.port=8083

# Database
spring.datasource.url=jdbc:postgresql://localhost:5435/rxpharma_db
spring.datasource.username=rxpharma_user
spring.datasource.password=rxpharma_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.repair-on-migrate=true

# JWT
jwt.secret=your-super-secret-key-change-this-in-production-min-256-bits
jwt.expiration=86400000

server.error.include-message=always
server.error.include-binding-errors=always